version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: it-graph
    ports:
      - "8080:8080"
    environment:
      QUARKUS_PROFILE: docker
    depends_on:
      - postgres
    networks:
      - it-graph_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itgraph
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5442:5432"
    networks:
      - it-graph_network
    volumes:
      - ${HOME}/it-graph:/var/lib/postgresql/data

networks:
  it-graph_network:
